### ISSUE TITLE
Feature request: integrate new working directory functionality

### ISSUE THREAD

**Issue by cyberixae** [GoogleChromeLabs/wasi-fs-access#2]
The working directory error message points to a solved upstream issue https://github.com/WebAssembly/WASI/issues/303

**Comment by RReverser** [comment]
Yup, looks like current working directory is now a thing in WASI. Do you want to try and make a PR to add its support?

**Comment by cyberixae** [comment]
Probably can't find the time in the near future to study this further.

**Comment by RReverser** [comment]
Looks like the issue of WASI itself not having a concept of current working directory still stands. I've commented on the upstream thread, let's see if we can get this resolved.

**Comment by RReverser** [comment]
Oh btw, this was integrated.
