### ISSUE TITLE
error build project with error Object is of type 'unknown'.

### ISSUE THREAD

**Issue by zababurinsv** [GoogleChromeLabs/wasi-fs-access#4]
I want build this project.

1. yarn install
2. yarn build

And i getting this error
```
src/browser.ts:307:20 - error TS2571: Object is of type 'unknown'.

307       term.writeln(err.message);
                       ~~~

src/fileSystem.ts:171:15 - error TS2571: Object is of type 'unknown'.

171           if (err.name === 'TypeMismatchError') {
                  ~~~

src/fileSystem.ts:184:13 - error TS2571: Object is of type 'unknown'.

184         if (err.name === 'TypeMismatchError') {
                ~~~

src/test.ts:134:25 - error TS2571: Object is of type 'unknown'.

134               message = err.message;
                            ~~~


Found 4 errors.

```

Howe can i resolve this error ?

**Comment by RReverser** [comment]
Ah right, I saw somewhere that TypeScript changed errors to have `unknown` type in some recent release. The error needs to be cast to `Error` type - if you can send a PR, that would be welcome.

**Comment by zababurinsv** [comment]
> Ah right, I saw somewhere that TypeScript changed errors to have `unknown` type in some recent release. The error needs to be cast to `Error` type - if you can send a PR, that would be welcome.



i am added type `any` for error.       
[err => err: any](https://github.com/GoogleChromeLabs/wasi-fs-access/compare/main...zababurinsv:zb?expand=1)

It will be right ?

**Comment by RReverser** [comment]
Does `err: Error` work in that context? If so, that would be even better, because it would typecheck the properties.

**Comment by zababurinsv** [comment]
> Error

In my IDE (CLion) i get error and this annotation
> TS1196: Catch clause variable type annotation must be 'any' or 'unknown' if specified

I understand that any or undefined type must be specified.
I'm not sure if I understand correctly.

![image](https://user-images.githubusercontent.com/22741813/138463354-3d2cff6c-725c-4d7f-90fe-e7ca7ec5d1f2.png)


I'll try again.

**Comment by RReverser** [comment]
I see. In that case, reverting to `err: any` sounds good for now. Please send a PR.

**Comment by zababurinsv** [comment]
> I see. In that case, reverting to `err: any` sounds good for now. Please send a PR.

I create new commit with type Error

https://github.com/GoogleChromeLabs/wasi-fs-access/compare/main...zababurinsv:zb?expand=1

It is ok ? If the first option is better, then I'll leave it and send a PR

**Comment by RReverser** [comment]
Yeah this looks good IMO.
